Feature/PDEV-1152: Add "sublabel" field
srstomp/structoform pull request #25
Opened 2022-05-03 14:45 UTC by robb216

Allows the form builder to render sublabels. Useful for "optional" labels, e.g.

![image](https://user-images.githubusercontent.com/17108331/166476128-b8f0833a-f0d0-4871-b2e0-f3b0779297fc.png)

2022-05-04 09:03 UTC, AlecHoefsmid approved these changes

2022-05-04 14:54 UTC, tomfrio requested changes

2022-05-04 14:54 UTC, tomfrio commented on package.json
> +    "version": "1.1.41",
Dit lijkt me eerder `1.2.0`; je voegt een nieuwe feature toe.

2022-05-04 14:54 UTC, tomfrio commented on src/components/FormItem.jsx
>  FormItem.propTypes = {
De propType voor `subLabel` mist nog.

2022-05-04 14:54 UTC, tomfrio commented on src/components/FormItem.jsx
> +            {!_.isNil(subLabel) && <span className={`form-item__sublabel`}>{subLabel}</span>}
Wil je hier niet _ook_ checken op een lege string?

2022-05-17 14:16 UTC, robb216 commented on package.json
> +    "version": "1.1.41",
Eens! Aangepast

2022-05-17 14:16 UTC, robb216 commented on src/components/FormItem.jsx
>  FormItem.propTypes = {
thanks, geüpdate

2022-05-17 14:18 UTC, robb216 commented on src/components/FormItem.jsx
> +            {!_.isNil(subLabel) && <span className={`form-item__sublabel`}>{subLabel}</span>}
bij nader inzien, inderdaad

2022-08-18 09:01 UTC, merged